<a href="https://colab.research.google.com/github/Subrat-GitHub/DSFEB20/blob/main/Copy_of_Updated_Python_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Python, Be good with me")


Python, Be good with me


In [2]:
import math
print(10+20)
math.sqrt(100)


30


10.0

In [3]:
60-20

40

In [4]:
40*2


80

In [5]:
import math
math.sqrt(64)

8.0

In [6]:
8 !=9


True

In [7]:
9==9


True

In [8]:
7<6

False

In [9]:
(7>6) & (3>5)

False

In [10]:
not((7>6)|(6<3))

False

In [11]:
i=0
while i<10:
  print (i)
  i=i+1

0
1
2
3
4
5
6
7
8
9


In [12]:
i=0
while i<10:
  print (i)
  i=i+1
print("Good job")  

0
1
2
3
4
5
6
7
8
9
Good job


In [13]:
i=0
while i<10:
  print (i)
  i=i+1
  print("Good job")  

0
Good job
1
Good job
2
Good job
3
Good job
4
Good job
5
Good job
6
Good job
7
Good job
8
Good job
9
Good job


In [14]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
for i in range(10):
  print(i)


0
1
2
3
4
5
6
7
8
9


In [16]:
list1 = ['Subrat', 10, True]
for i in list1:
  print(i)

Subrat
10
True


In [17]:
import numpy as np
from numpy.random import randn 
x=randn()
x


1.4439899455529401

In [18]:
x = randn()
result = 'None'
if x>1:
  result ="Greater than 1"
print(x)
print(result)

2.3015722294963488
Greater than 1


In [19]:
x = randn()
result = 'None'
if x>1:
  result ="Greater than 1"
else:
  result ="Less than 1"
print(x)
print(result)

-0.04730367760944831
Less than 1


In [20]:
x = randn()
result = 'None'
if x>1:
  result ="Greater than 1"
elif x>=-1:
  result ="Between -1 and 1"
else:
  result ="Less than -1"
print(x)
print(result)

0.37611307419764006
Between -1 and 1


In [21]:
x = randn()
result = 'None'
if x>1:
  result ="Greater than 1"
elif x>=-1:
  result ="Between -1 and 1"
else:
  result ="Less than -1"
print("Hello Python")
print(x)
print(result)

Hello Python
1.5340379476138462
Greater than 1


In [22]:
letters = ['A','B','C','D','E','F','G','H','I','J']
letters[1:6] # start index,end index+1
letters[-1]

'J'

In [23]:
letters[0]


'A'

In [24]:
letters[0:8:2] # start index, end index+1, interval

['A', 'C', 'E', 'G']

In [25]:
letters[1:8:2]

['B', 'D', 'F', 'H']

In [26]:
letters[-9:-1:2]


['B', 'D', 'F', 'H']

In [27]:
letters[1::2]

['B', 'D', 'F', 'H', 'J']

In [28]:
letters[::3]

['A', 'D', 'G', 'J']

In [29]:
letters[:7]

['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [30]:
letters[7:]

['H', 'I', 'J']

In [32]:
  #String, float, int, boolean -> Hierarchy

In [35]:
tuple1=(56,72,'Subrat')
tuple1[1]

72

In [37]:
# Tuples should be used when there should not be any change



In [40]:
mylist1 = list(range(30,41))
print(mylist1)

[30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]


In [41]:
len(mylist1)

11

In [42]:
type(mylist1)

list

In [56]:
max(mylist1)

40

In [57]:
list6 = [1,30.6,False]
b = np.array(list6)
b

array([ 1. , 30.6,  0. ])

In [59]:
list7 = [1,False]
c = np.array(list7)
c

array([1, 0])

In [60]:
list8 = [False]
d = np.array(list8)
d

array([False])

In [45]:
min(mylist1)

30

In [47]:
max("processwhirlz")

'z'

In [51]:
min("subrat")


'a'

In [52]:
list5 = [1,'Brad',30.6, True]


In [54]:
a = np.array(list5)

In [55]:
a

array(['1', 'Brad', '30.6', 'True'], dtype='<U32')

In [ ]:
# Slicing in arrays